https://datahacker.rs/002-pytorch-what-are-tensors-in-pytorch-1-3/

```
# Creating tensors in PyTorch
```



In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
# Create a 1D Tensor/Vector
vector_data = [2,3,5,7,11]
vector = torch.tensor(vector_data)
print(vector, end='\n\n')

tensor([ 2,  3,  5,  7, 11])



In [3]:
# Create a 2D Tensor of size 2x3
matrix_data = [[1,2,3],[4,5,6]]
matrix = torch.tensor(matrix_data)
print(matrix, end='\n\n')

tensor([[1, 2, 3],
        [4, 5, 6]])



In [4]:
# Create a 3D Tensor of size 3x2x2
Tensor_data = [[[20., 40.], [60., 80.]],
          [[100., 120.], [140., 160.]],
          [[180., 200.], [220., 240.]]]
Tensor = torch.tensor(Tensor_data)
print(Tensor, end='\n\n')

tensor([[[ 20.,  40.],
         [ 60.,  80.]],

        [[100., 120.],
         [140., 160.]],

        [[180., 200.],
         [220., 240.]]])



```
# Indexing using PyTorch
```



In [5]:
# Indexing into vector and get a scalar
print(vector[0],'\n')

# Get a Python number from it
print(vector[0].item())

tensor(2) 

2


In [6]:
# Indexing into Matrix and get a vector
print(matrix[0],end='\n\n')

# Indexing into Tensor and get a matrix
print(Tensor[0])

tensor([1, 2, 3])

tensor([[20., 40.],
        [60., 80.]])


```
# Operations with Tensors
```

In [7]:
x = torch.tensor([1,0])
y = torch.tensor([3,4])

In [8]:
# Addition

print(torch.add(x,y),end='\n\n')

z = x+y
print(z)

tensor([4, 4])

tensor([4, 4])


In [9]:
# Subtruction
print(torch.sub(y,x),end='\n\n')

z =y-x
print(z)

tensor([2, 4])

tensor([2, 4])


In [10]:
print(torch.mul(x,y),end='\n\n')

z = x*y
print(z)

tensor([3, 0])

tensor([3, 0])


In [11]:
print(torch.div(x,y),end='\n\n')

z = y/x
print(z)

tensor([0.3333, 0.0000])

tensor([3., inf])


In [12]:
# Concatenate columns: Row-wise, axis=0 is by default.
a_1 = torch.randn(2, 2)
b_1 = torch.randn(2, 2)
print(a_1 ,'\n\n', b_1,'\n\n')
c_1 = torch.cat([a_1, b_1], axis=0)
print(c_1)


tensor([[0.1736, 1.1388],
        [1.0952, 0.3122]]) 

 tensor([[-0.2539,  0.7048],
        [ 0.4776,  0.0152]]) 


tensor([[ 0.1736,  1.1388],
        [ 1.0952,  0.3122],
        [-0.2539,  0.7048],
        [ 0.4776,  0.0152]])


In [13]:
# Concatenate columns: Column-wise, axis=1.
c_1 = torch.cat([a_1, b_1], axis=1)
print(c_1)

tensor([[ 0.1736,  1.1388, -0.2539,  0.7048],
        [ 1.0952,  0.3122,  0.4776,  0.0152]])


```
# Reshaping Tensors
```

In [14]:
x = torch.randn(3, 8)
print(x)
print(x.shape)

tensor([[-1.4940, -0.4810, -2.2394, -0.8013, -0.6403,  0.6742,  0.6646,  0.5300],
        [ 1.0057,  0.0970,  0.1667, -1.6581, -0.3347, -0.2616, -0.0131,  1.2536],
        [-0.8892,  1.6404,  0.2120, -0.9741, -0.0430, -0.0700, -0.0742, -0.7920]])
torch.Size([3, 8])


In [15]:
y = x.view(4,6) # Reshape to 4 rows, 6 columns
print(y)
print(y.shape)

tensor([[-1.4940, -0.4810, -2.2394, -0.8013, -0.6403,  0.6742],
        [ 0.6646,  0.5300,  1.0057,  0.0970,  0.1667, -1.6581],
        [-0.3347, -0.2616, -0.0131,  1.2536, -0.8892,  1.6404],
        [ 0.2120, -0.9741, -0.0430, -0.0700, -0.0742, -0.7920]])
torch.Size([4, 6])


In [16]:
# Same as above. If one of the dimensions is -1, its size can be deduced
print(x.view(4, -1))

tensor([[-1.4940, -0.4810, -2.2394, -0.8013, -0.6403,  0.6742],
        [ 0.6646,  0.5300,  1.0057,  0.0970,  0.1667, -1.6581],
        [-0.3347, -0.2616, -0.0131,  1.2536, -0.8892,  1.6404],
        [ 0.2120, -0.9741, -0.0430, -0.0700, -0.0742, -0.7920]])


In [17]:
print(x.view(-1, 4))

tensor([[-1.4940, -0.4810, -2.2394, -0.8013],
        [-0.6403,  0.6742,  0.6646,  0.5300],
        [ 1.0057,  0.0970,  0.1667, -1.6581],
        [-0.3347, -0.2616, -0.0131,  1.2536],
        [-0.8892,  1.6404,  0.2120, -0.9741],
        [-0.0430, -0.0700, -0.0742, -0.7920]])


```
# NumPy to Torch and back
```

In [18]:
import numpy as np # Numerical Python

X = np.random.randn(4, 4) # Generate random numbers
print(X, end='\n\n')
print(type(X)) # A numpy array

[[ 0.66263867  0.33556587  0.74894525  2.05107675]
 [ 1.13056004 -0.18324334  0.2568282   0.57054188]
 [-1.57063069 -0.43631628  1.16188008 -0.17159912]
 [ 0.07786757  1.46340837  0.68023812 -0.98010017]]

<class 'numpy.ndarray'>


In [19]:
a = torch.from_numpy(X) # Convert to tensor
print(a, end='\n\n')
print(type(a)) # A torch tensor

tensor([[ 0.6626,  0.3356,  0.7489,  2.0511],
        [ 1.1306, -0.1832,  0.2568,  0.5705],
        [-1.5706, -0.4363,  1.1619, -0.1716],
        [ 0.0779,  1.4634,  0.6802, -0.9801]], dtype=torch.float64)

<class 'torch.Tensor'>


In [20]:
y = a.numpy()# Convert the tensor into NumPy array
print(type(y))

<class 'numpy.ndarray'>


```
# Autograd
```

In [21]:
x = torch.ones(1, requires_grad=True)
print(x)

tensor([1.], requires_grad=True)


In [22]:
y = 6*x**2
print(y)

tensor([6.], grad_fn=<MulBackward0>)


In [23]:
print(x.grad, end='\n\n')
# print(y.grad)

None



`f'(x) = d/dx (6x²) = 2* 6x = 2*6*1 = 12`

In [24]:
y.backward() # gradients are computed with respect to our tensor 𝑥 with
print(x.grad)

tensor([12.])
